networks:
  default:
    name: roboshop
    driver: bridge
volumes:
  mongodb:
  redis:
  mysql:
  rabbitmq:
services:
  mongodb:
    image: msivakmrreddy/mongodb:v1
    container_name: mongodb
    volumes:
    - mongodb:/data/db
  catalogue:
    image: msivakmrreddy/catalogue:v1
    container_name: catalogue
    depends_on:
    - mongodb
  redis:
    image: redis:7.0
    container_name: redis
    volumes:
    - redis:/data
  user:
    image: msivakmrreddy/user:v1
    container_name: user
    depends_on:
    - redis
  cart:
    image: msivakmrreddy/cart:v1
    container_name: cart
    depends_on:
    - redis
  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: roboshop
      RABBITMQ_DEFAULT_PASS: roboshop123
    volumes:
    - rabbitmq:/var/lib/rabbitmq
  mysql:
    image: msivakmrreddy/mysql:v1
    container_name: mysql
    volumes:
    - mysql:/var/lib/mysql
  shipping:
    image: msivakmrreddy/shipping:v1
    container_name: shipping
    depends_on:
    - mysql
  payment:
    image: msivakmrreddy/payment:v1
    container_name: payment
    depends_on:
    - rabbitmq
  frontend:
    image: msivakmrreddy/frontend:v1
    container_name: frontend
    ports:
    - "80:80"
    depends_on:
    - catalogue
    - user
    - cart
    - shipping
    - payment